/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/confirm`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/consent`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-handle`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/safety`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/triage`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/counselors`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/resources`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/confirm`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/consent`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/create-handle`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/safety`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/triage`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/counselors`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/resources`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/onboarding/confirm${`?${string}` | `#${string}` | ''}` | `/onboarding/consent${`?${string}` | `#${string}` | ''}` | `/onboarding/create-handle${`?${string}` | `#${string}` | ''}` | `/onboarding/location${`?${string}` | `#${string}` | ''}` | `/onboarding/safety${`?${string}` | `#${string}` | ''}` | `/onboarding/sign-in${`?${string}` | `#${string}` | ''}` | `/onboarding/triage${`?${string}` | `#${string}` | ''}` | `/tabs/chat${`?${string}` | `#${string}` | ''}` | `/tabs/counselors${`?${string}` | `#${string}` | ''}` | `/tabs/dashboard${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | `/tabs/resources${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/confirm`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/consent`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-handle`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/location`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/safety`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/triage`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/counselors`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/resources`; params?: Router.UnknownInputParams; };
    }
  }
}
